[package]
name = "simple-strength-assistant"
version = "0.1.0"
edition = "2024"
authors = ["rob-mur"]
description = "A simple strength training assistant built with Rust and Dioxus"
license = "AGPLv3"

[dependencies]
dioxus = { version = "0.6", features = ["web"] }
